language: go
go_import_path: github.com/bert42/alien-invasion
go:
  - 1.10.x
sudo: false
install:
  - GOPATH=$TRAVIS_BUILD_DIR go get -d -v ./...
script:
  - GOPATH=$TRAVIS_BUILD_DIR go test ./src/invasion/...
