language: go
go_import_path: github.com/bert42/alien-invasion
go:
  - 1.10.x
  - tip
sudo: false
install:
  - go get github.com/davecgh/go-spew/spew
  - go build cmd/alien-invasion/main.go
script:
  - go test -v cmd/alien-invasion/invasion_test.go
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
