language: go
go_import_path: github.com/bert42/alien-invasion
go:
  - 1.10.x
sudo: false
install:
  - go get -d -v ./...
script:
  - go test ./cmd/...
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
